version: '3.8'
services:
  vis-playground:
    build:
      context: ./vis-playground
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
  viscom_backend:
    build:
      context: ./viscom_backend
    ports:
      - "5000:5000"
